@startuml
frame Game  {
 [creeps]
 [structures]
 [constructionSites]
}

frame agents {
  frame Creep {
    [Engineer]
    [Harvester]
    [Miner]
  }
  frame Structure {
    [Spawn]
    [Tower]
  }
  [Room]
}

dataBase Model {
  dataBase Memory {
    [roomInfo]
    [gameInfo]
  }
}
package View {
  () jobQueue
  () spawnQueue
  () buildQueue
}
package Controller {
  [Strategy]
  () agentInput - [Strategy]
}

[main] -- loop
loop ---> Room : run()
loop ---> [logger] : run()
loop ---> Controller: run()

View --> agentInput: agent input

Room --> Creep: run()
Room --> Structure : run()

[Strategy] --> Model  : update data
Controller --> View : update view
Model --> Controller : notify change

' [logger] ..> Memory : read

jobQueue <.. Creep: getJob()
spawnQueue <.. Spawn: getSpawnJob()
@enduml
