@startuml ComponentAgents

frame agents {
  frame Creep {
    [Engineer]
    [Harvester]
    [Miner]
  }
  frame Structure {
    [Spawn]
    [Tower]
  }
  [Room]
}

package gameDirector {
  [GameDirector]
}
dataBase gameModel {
  () numberOfRooms
}
GameDirector - gameModel


package roomDirector {
  [RoomDirector]
}
dataBase roomModel {
  () constructionSites
  () restockQueue
  () JobsInRoom
  () jobDemand
  () rolesInRoom
  () spawnQueue
  () buildQueue
}
RoomDirector - roomModel

[main] -- loop
loop ---> GameDirector: run()
GameDirector --> RoomDirector: run()

RoomDirector --> Creep: run()
RoomDirector --> Structure : run()


@enduml
