@startuml
title MVC sequence each tick

  Boundary Game
  Control Controller
  Database Model

group Initialization
    Game <- Controller: read()
    Game --> Controller: gameInfo
    Controller -> Model: initialize()
end

group Game loop
  == start of tick ==
  Game <- Controller: Monitor()
  Game --> Controller: gameInfo
  Controller -> Model: manipulate()
  Model -> View: update()

  == during tick ==
  ... agent request...
  actor agent
  View <- agent: getJob()
  View --> agent: job[0]
  View -> Controller: Queue--
  ... ...
  == end of tick ==
end
@enduml
